=== AdrianLuqRod/Markup/DTD/ej11/11.dtd
<!ELEMENT alumnado (alumno+)>
<!ELEMENT alumno (datos-personales,equipo-deportivo?,aficiones?,comentarios?,notas?)>
<!ELEMENT datos-personales (nombre,apellidos,domicilio,telefonos*,lugar-nacimiento,altura?,sexo?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT domicilio (#PCDATA)>
<!ELEMENT telefonos (telefono+)>
<!ELEMENT telefono (#PCDATA)>
<!ATTLIST telefono tipo (propio | padre | madre | tutor) #IMPLIED>
<!ELEMENT lugar-nacimiento (#PCDATA)>
<!ELEMENT altura (#PCDATA)>
<!ELEMENT sexo (Hombre | Mujer)>
<!ELEMENT equipo-deportivo (#PCDATA)>
<!ELEMENT aficiones (aficion+)>
<!ELEMENT aficion (#PCDATA)>
<!ELEMENT comentarios (comentario+)>
<!ELEMENT comentario (#PCDATA)>
<!ELEMENT notas (nota+)>
<!ELEMENT nota (#PCDATA | evaluacion | calificacion)*>

=== AdrianLuqRod/Markup/DTD/ej11/11.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alumnado SYSTEM "11.dtd">
<alumnado>
    <alumno>
        <datos-personales>
            <nombre>Adrian</nombre>
            <apellidos>Luque</apellidos>
            <domicilio>Rodriguez</domicilio>
            <telefonos>
                <telefono tipo="propio">618554433</telefono>
                <telefono>954112233</telefono>
            </telefonos>
            <lugar-nacimiento>Mi casa</lugar-nacimiento>
        </datos-personales>
        <equipo-deportivo>Nothingam Miedo FC</equipo-deportivo>
        <aficiones>
            <aficion>Cine</aficion>
            <aficion>Ajedrez</aficion>
        </aficiones>
        <comentarios>
            <comentario>Excelente, ha hecho sus ejercicios</comentario>
        </comentarios>
        <notas>
            <nota>7</nota>
            <nota>10</nota>
            <nota>8</nota>
        </notas>
    </alumno>
</alumnado>
