=== AdrianLuqRod/Markup/DTD/ej10/10.dtd
<!ELEMENT clientes-empresa (cliente+)>

<!ELEMENT cliente (nombre,apellidos,dispositivos)>
<!ATTLIST cliente id ID #REQUIRED>
<!ATTLIST cliente dni CDATA #REQUIRED>
<!ATTLIST cliente telefono CDATA #REQUIRED>
<!ATTLIST cliente email CDATA #IMPLIED>

<!ELEMENT nombre (#PCDATA)>

<!ELEMENT apellidos (#PCDATA)>

<!ELEMENT dispositivos (dispositivo+)>

<!ELEMENT dispositivo (marca,modelo,reparaciones?)>
<!ATTLIST dispositivo propietario IDREF #REQUIRED>
<!ATTLIST dispositivo tipo (sobremesa | portÃ¡til | smartphone | monitor | televisor | tablet | otros) #REQUIRED>

<!ELEMENT tipo (#PCDATA)>

<!ELEMENT marca (#PCDATA)>

<!ELEMENT modelo (#PCDATA)>

<!ELEMENT reparaciones (reparacion+)>

<!ELEMENT reparacion (fecha,descripcion,solucion)>
<!ATTLIST reparacion numHoras CDATA "1">

<!ELEMENT fecha (#PCDATA)>

<!ELEMENT descripcion (#PCDATA)>

<!ELEMENT solucion (#PCDATA)>

=== AdrianLuqRod/Markup/DTD/ej10/10.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE clientes-empresa SYSTEM "10.dtd">
<clientes-empresa>
    <cliente id="C1" dni="12654123T" telefono="965656333">
        <nombre>Juan</nombre>
        <apellidos>Luis Guerra</apellidos>
        <dispositivos>
            <dispositivo propietario="C1" tipo="portátil">
                <marca>Toshiba</marca>
                <modelo>Dynabook Tecra A40</modelo>
                <reparaciones>
                    <reparacion numHoras="2">
                        <fecha>2024-01-01</fecha>
                        <descripcion>La batería no funciona</descripcion>
                        <solucion>Cambio de batería</solucion>
                    </reparacion>
                </reparaciones>
            </dispositivo>
        </dispositivos>
    </cliente>
    <cliente id="C2" dni="62854854Z" telefono="918222333" email="luisml123@gmail.com">
        <nombre>Luis</nombre>
        <apellidos>Miguel López</apellidos>
        <dispositivos>
            <dispositivo propietario="C2" tipo="smartphone">
                <marca>Apple</marca>
                <modelo>iPhone X</modelo>
            </dispositivo>
            <dispositivo propietario="C2" tipo="tablet">
                <marca>Samsung</marca>
                <modelo>Tab A8</modelo>
            </dispositivo>
        </dispositivos>
    </cliente>
</clientes-empresa>
