=== AdrianLuqRod/Markup/XSD/ExamenPasado/empresas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!-- Declaramos el elemento empresas -->
    <xs:element name="empresas">
        <xs:complexType>
            <xs:sequence>
                <!-- Declaramos el elemento empresa -->
                <xs:element name="empresa" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="direccion" type="xs:string" />
                            <xs:element name="codigoPostal" type="xs:integer" />
                            <xs:element name="fechaConstitucion" type="xs:date" />
                            <xs:element name="energias">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="renovables">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="renovable" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="descripcion" type="xs:string" />
                                                                <xs:element name="ventajas" minOccurs="0">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="ventaja" minOccurs="2" maxOccurs="5" type="xs:string" />
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                                <xs:element name="desventajas" minOccurs="0">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="desventaja" minOccurs="2" maxOccurs="5" type="xs:string" />
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                                <xs:element name="facturacion" type="xs:decimal" />
                                                            </xs:sequence>
                                                            <xs:attribute name="procedencia" default="otras" />
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="noRenovables" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="noRenovable" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="descripcion" type="xs:string" />
                                                                <xs:element name="ventajas" minOccurs="0">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="ventaja" minOccurs="2" maxOccurs="5" type="xs:string" />
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                                <xs:element name="desventajas" minOccurs="0">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="desventaja" minOccurs="2" maxOccurs="5" type="xs:string" />
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                                <xs:element name="facturacion" type="xs:decimal" />
                                                            </xs:sequence>
                                                            <xs:attribute name="procedencia" default="otras" />
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="cif" use="required" />
                        <xs:attribute name="telefono" type="xs:integer" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== AdrianLuqRod/Markup/XSD/ExamenPasado/empresas.xml
<?xml version="1.0" encoding="UTF-8"?>
<empresas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="empresas.xsd">
    <empresa cif="A12345678" telefono="616987654">
        <nombre>Sotero Energías</nombre>
        <direccion>C/ Santo Domingo de Guzmán S/N</direccion>
        <codigoPostal>41920</codigoPostal>
        <fechaConstitucion>2022-02-24</fechaConstitucion>
        <energias>
            <renovables>
                <renovable procedencia="solar">
                    <descripcion>Es aquella que obtenemos del sol.</descripcion>
                    <ventajas>
                        <ventaja>Es una energía limpia, renovable y sostenible.</ventaja>
                        <ventaja>Es una fuente renovable e inagotable que se puede utilizar en todo el planeta.</ventaja>
                    </ventajas>
                    <desventajas>
                        <desventaja>Inversión inicial.</desventaja>
                        <desventaja>Dependencia del clima.</desventaja>
                    </desventajas>
                    <facturacion>15550.99</facturacion>
                </renovable>
            </renovables>
            <noRenovables>
                <noRenovable procedencia="petroleo">
                    <descripcion>Es un combustible fósil.</descripcion>
                    <ventajas>
                        <ventaja>Es de fácil almacenamiento.</ventaja>
                        <ventaja>Su obtención es continua.</ventaja>
                    </ventajas>
                    <desventajas>
                        <desventaja>Es muy contaminante, debido a la combustión.</desventaja>
                        <desventaja>Genera contaminación por derrames.</desventaja>
                    </desventajas>
                    <facturacion>120000</facturacion>
                </noRenovable>
            </noRenovables>
        </energias>
    </empresa>
</empresas>
