=== AdrianLuqRod/Markup/XSD/Ejercicio04/e04.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="catalogo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="producto" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="vendedor" minOccurs="0" type="xs:string" />
                            <xs:element name="precio" type="xs:decimal" />
                            <xs:element name="detalle" minOccurs="0" maxOccurs="unbounded" type="xs:string" />
                            <xs:element name="opiniones" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="opinion" maxOccurs="unbounded" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== AdrianLuqRod/Markup/XSD/Ejercicio04/e04.xml
<?xml version="1.0" encoding="UTF-8"?>
<catalogo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="e04.xsd">
    <producto>
        <nombre>Teclado inal√°mbrico Zeus 23Q</nombre>
        <vendedor>Todo Teclados</vendedor>
        <precio>23.90</precio>
        <detalle>Opera en la frecuencia de 2.4 GHz</detalle>
        <detalle>Hasta 20 metros de distancia</detalle>
    </producto>
    <producto>
        <nombre>Smartwatch Pulserita Wear</nombre>
        <precio>120.90</precio>
        <opiniones>
            <opinion>Mi abuela me toma mejor el pulso</opinion>
            <opinion>No es resistente al agua</opinion>
        </opiniones>
    </producto>
</catalogo>
