=== AdrianLuqRod/Markup/DTD/ej08/08.dtd
<!ELEMENT venta-vehiculos (vehiculo+)>
<!ELEMENT vehiculo (marca, modelo, propietario?)>
<!ATTLIST vehiculo matricula CDATA "0000-AAA">
<!ELEMENT marca (#PCDATA)>
<!ELEMENT modelo (#PCDATA)>
<!ELEMENT propietario (#PCDATA)>
<!ATTLIST propietario dni CDATA #REQUIRED>

=== AdrianLuqRod/Markup/DTD/ej08/08.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE venta-vehiculos SYSTEM "08.dtd">
<venta-vehiculos>
    <vehiculo matricula="4534-FRG">
        <marca>Seat</marca>
        <modelo>Ibiza</modelo>
        <propietario DNI="12654123T">Juan Luis Guerra</propietario>
    </vehiculo>

    <vehiculo matricula="8333-ABC">
        <marca>Volvo</marca>
        <modelo>S40</modelo>
        <propietario DNI="62854854Z">Luis Miguel LÃ³pez</propietario>
    </vehiculo>

    <vehiculo matricula="1234-ZAP">
        <marca>Seat</marca>
        <modelo>Toledo</modelo>
        <propietario></propietario>
    </vehiculo>

    <vehiculo>
        <marca>Fiat</marca>
        <modelo>Punto</modelo>
        <propietario></propietario>
    </vehiculo>
</venta-vehiculos>
